export const SET_RECENTLY_PLAYLISTS = "SET_RECENTLY_PLAYLISTS";
export const SET_FEATURED_PLAYLISTS = "SET_FEATURED_PLAYLISTS";
export const SET_MOOD_PLAYLISTS = "SET_MOOD_PLAYLISTS";
export const SET_HEADER_TITLE = "SET_HEADER_TITLE";
export const SET_HEADER_DESCRIPTION = "SET_HEADER_DESCRIPTION";
export const SET_HEADER_LENGTH = "SET_HEADER_LENGTH";
export const SET_HEADER_DURATION = "SET_HEADER_DURATION";
export const SET_HEADER_IMAGE = "SET_HEADER_IMAGE";
